###############################################
# Configure the volumes for the Docker Engine
###############################################
- name: Create a new primary partition in /dev/vdb for the volume
  parted:
    device: /dev/vdb
    number: 1
    state: present

- name: Create a ext4 filesystem on /dev/vdb1 and check disk blocks
  filesystem:
    fstype: ext4
    dev: /dev/vdb1
    opts: -cc

# - name: Create the corresponding /var/docker/volume folder

- name: Mount the partition in /var/lib/docker/volumes with mount and modify fstab
  mount:
    path: /var/lib/docker/volumes
    src: /dev/vdb1
    fstype: ext4
    opts: defaults
    state: mounted
